[package]
name = "contenant"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "*", features = ["derive"] }
facet = "0.42.0"
facet-kdl = "0.42.0"
sha2 = "*"
xdg = "*"

[build-dependencies]
sha2 = "*"
