[package]
name = "contenant"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "*", features = ["derive"] }
mlua = { version = "*", features = ["lua54", "vendored", "serde"] }
serde = { version = "*", features = ["derive"] }
sha2 = "*"
xdg = "*"

[build-dependencies]
sha2 = "*"
