[package]
name = "contenant"
version = "0.1.0"
edition = "2024"

[build-dependencies]
sha2 = "*"

[dependencies]
tracing = "*"
tracing-subscriber = { version = "*", features = ["env-filter"] }
xdg = "*"
